### ISSUE TITLE
Add API version

### ISSUE THREAD

**Issue by mmoreram** [puntmig/javascript-search-client#1]
JS client should manage the API version.
That would mean that, by default, used API is v1, but people should be able to change it in the future.

`version: v1 (default)`

Desired version will be prepended into all API urls.

`/v1/xxx/yyy`

**Comment by alexhoma** [comment]
**Done.** Currently this is the full setup of the Apisearch client:

```javascript
const api = apisearch({
    appId: "music_app",
    apiKey: "1cc7a3e0-bda5-11e7-abc4-cec278b6b50a",
    options: {
        endpoint: "http://puntmig.net", // it has this endpoint by default
        apiVersion: "v1",               // "v1" is the only and the default api version 
        cache: true                     // set to true by default 
    }
});
```

**Comment by mmoreram** [comment]
@alexhoma what does this cache means?

**Comment by alexhoma** [comment]
It refers to a javascript in memory cache. This is useful to avoid querying data when the user deletes his text search on an input box, for example.

Due to Apisearch server cache, we add a new parameter called `http` on a cache options object. To specify the TTL of the cache in seconds.
```javascript
options: {
    endpoint: "http://puntmig.net", // it has this endpoint by default
    apiVersion: "v1",               // "v1" is the only and the default api version 
    cache: {
        inMemory: true, // javascript in memory cache (default true)
        http: 0         // http cache, TTL in seconds (default 0)
    }
}
```
